force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Last_Fertilization__c.field-meta.xml
<CustomField>
    <fullName>Last_Fertilization__c</fullName>
    <label>Last Fertilization</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Last_Watered__c.field-meta.xml
<CustomField>
    <fullName>Last_Watered__c</fullName>
    <label>Last Watered</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Next_Fertilization__c.field-meta.xml
<CustomField>
    <fullName>Next_Fertilization__c</fullName>
    <label>Next Fertilization</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Next_Water__c.field-meta.xml
<CustomField>
    <fullName>Next_Water__c</fullName>
    <label>Next Water</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Species</label>
    <referenceTo>Species__c</referenceTo>
    <relationshipLabel>Plants</relationshipLabel>
    <relationshipName>Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Species__c/fields/Fertilization__c.field-meta.xml
<CustomField>
    <fullName>Fertilization__c</fullName>
    <label>Fertilization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low (cada mes)</fullName>
            </value>
            <value>
                <fullName>Medium (cada 2 semanas)</fullName>
            </value>
            <value>
                <fullName>High (semanal)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Species__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoors</fullName>
            </value>
            <value>
                <fullName>Outdoors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Species__c/fields/Locationes__c.field-meta.xml
<CustomField>
    <fullName>Locationes__c</fullName>
    <description>Región y clima ideal para la especie</description>
    <label>Locationes</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tropical (Amazonas, sureste asiático)</fullName>
            </value>
            <value>
                <fullName
        >Tropical de Sabana (África subsahariana, sur de India)</fullName>
                <label
        >Tropical de Sabana (África subsahariana, sur de India)</label>
            </value>
            <value>
                <fullName
        >Subtropical (Sureste de EE. UU., sur de Brasil, este de Asia)</fullName>
                <label
        >Subtropical (Sureste de EE. UU., sur de Brasil, este de Asia)</label>
            </value>
            <value>
                <fullName
        >Mediterráneo (Sur de Europa, California, Chile central)</fullName>
                <label
        >Mediterráneo (Sur de Europa, California, Chile central)</label>
            </value>
            <value>
                <fullName
        >Templado Oceánico (Inglaterra, noroeste de EE. UU., sur de Chile)</fullName>
                <label
        >Templado Oceánico (Inglaterra, noroeste de EE. UU., sur de Chile)</label>
            </value>
            <value>
                <fullName
        >Continental Húmedo (Noreste de EE. UU., Europa del Este, norte de China)</fullName>
                <label
        >Continental Húmedo (Noreste de EE. UU., Europa del Este, norte de China)</label>
            </value>
            <value>
                <fullName>Alta Montaña (Andes, Himalaya, Alpes)</fullName>
            </value>
            <value>
                <fullName>Árido/Desértico (Sáhara, Sonora, Atacama)</fullName>
            </value>
            <value>
                <fullName
        >Semiárido/Estepa (Centro de España, Patagonia, Grandes Llanuras)</fullName>
                <label
        >Semiárido/Estepa (Centro de España, Patagonia, Grandes Llanuras)</label>
            </value>
            <value>
                <fullName
        >Continental Frío/Subártico (Siberia, norte de Canadá, Escandinavia)</fullName>
                <label
        >Continental Frío/Subártico (Siberia, norte de Canadá, Escandinavia)</label>
            </value>
            <value>
                <fullName
        >Húmedo Insular (Hawaii, Islas Canarias, Madeira)</fullName>
                <label>Húmedo Insular (Hawaii, Islas Canarias, Madeira)</label>
            </value>
            <value>
                <fullName
        >Transición (Sur de Brasil, Uruguay, este de Paraguay)</fullName>
                <label
        >Transición (Sur de Brasil, Uruguay, este de Paraguay)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Species__c/fields/Whatering__c.field-meta.xml
<CustomField>
    <fullName>Whatering__c</fullName>
    <label>Watering</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low (1 vez por semana)</fullName>
            </value>
            <value>
                <fullName>Medium (2-3 veces por semana)</fullName>
            </value>
            <value>
                <fullName>High (diario)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlantServiceTest.cls
@isTest
private with sharing class PlantServiceTest {
  @TestSetup
  static void createData() {
    String locationesValue = 'Tropical (Amazonas, sureste asiático)';

    Species__c aloeVera = new Species__c(
      Name = 'Aloe Vera',
      Whatering__c = 'Low (1 vez por semana)',
      Fertilization__c = 'Low (cada mes)',
      Location__c = 'Indoors',
      Locationes__c = locationesValue
    );
    insert aloeVera;
  }

  @isTest
  static void testCalculateNextWateringDate() {
    Species__c specie = [SELECT Id, Whatering__c FROM Species__c LIMIT 1];
    Plant__c plant = new Plant__c(
      Species__c = specie.Id,
      Last_Watered__c = System.today(),
      Last_Fertilization__c = System.today()
    );
    PlantService plantService = new PlantService();
    plantService.calculateNextWateringDate(new List<Plant__c>{ plant });
    System.assertEquals(
      System.today().addDays(7),
      plant.Next_Water__c,
      'Next_Water__c should be 7 days after Last_Watered__c'
    );
  }

  @isTest
  static void testCalculateNextFertilizationDate() {
    Species__c specie = [SELECT Id, Fertilization__c FROM Species__c LIMIT 1];
    Plant__c plant = new Plant__c(
      Species__c = specie.Id,
      Last_Watered__c = System.today(),
      Last_Fertilization__c = System.today()
    );
    PlantService plantService = new PlantService();
    plantService.calculateNextFertilizationDate(new List<Plant__c>{ plant });
    System.assertEquals(
      System.today().addDays(30),
      plant.Next_Fertilization__c,
      'Next_Fertilization__c should be 30 days after Last_Fertilization__c'
    );
  }
}