force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Last_Fertilization__c.field-meta.xml
<CustomField>
    <fullName>Last_Fertilization__c</fullName>
    <label>Last Fertilization</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Last_Watered__c.field-meta.xml
<CustomField>
    <fullName>Last_Watered__c</fullName>
    <label>Last Watered</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Next_Fertilization__c.field-meta.xml
<CustomField>
    <fullName>Next_Fertilization__c</fullName>
    <label>Next Fertilization</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Next_Water__c.field-meta.xml
<CustomField>
    <fullName>Next_Water__c</fullName>
    <label>Next Water</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Species</label>
    <referenceTo>Species__c</referenceTo>
    <relationshipLabel>Plants</relationshipLabel>
    <relationshipName>Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Species__c/fields/Fertilization__c.field-meta.xml
<CustomField>
    <fullName>Fertilization__c</fullName>
    <label>Fertilization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low (cada mes)</fullName>
            </value>
            <value>
                <fullName>Medium (cada 2 semanas)</fullName>
            </value>
            <value>
                <fullName>High (semanal)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Species__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoors</fullName>
            </value>
            <value>
                <fullName>Outdoors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Species__c/fields/Whatering__c.field-meta.xml
<CustomField>
    <fullName>Whatering__c</fullName>
    <label>Watering</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low (1 vez por semana)</fullName>
            </value>
            <value>
                <fullName>Medium (2-3 veces por semana)</fullName>
            </value>
            <value>
                <fullName>High (diario)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlantTriggerTest.cls
@isTest
private with sharing class PlantTriggerTest {
  // =========================================
  // TEST SETUP
  // =========================================

  @TestSetup
  static void createData() {
    Species__c aloeVera = new Species__c(
      Name = 'Aloe Vera',
      Whatering__c = 'Low (1 vez por semana)',
      Fertilization__c = 'Low (cada mes)',
      Location__c = 'Indoors'
    );

    insert aloeVera;
  }

  // =========================================
  // TEST NEXT WATER DATE
  // =========================================

  @isTest
  static void updatePlantNextWateringDateCalculatedCorrectly() {
    // ARRANGE

    Species__c specie = [
      SELECT Id
      FROM Species__c
      LIMIT 1
    ];

    Plant__c plant = new Plant__c(
      Species__c = specie.Id,
      Last_Watered__c = System.today(),
      Last_Fertilization__c = System.today()
    );

    // ACT

    Test.startTest();

    insert plant;

    Test.stopTest();

    // ASSERT

    plant = [
      SELECT Next_Water__c
      FROM Plant__c
      WHERE Id = :plant.Id
    ];

    System.assertEquals(
      System.today() + 7,
      plant.Next_Water__c,
      'La fecha de siguiente riego debe ser 7 dias despues del ultimo riego'
    );
  }

  // =========================================
  // TEST NEXT FERTILIZATION DATE
  // =========================================

  @isTest
  static void updatePlantNextFertilizationDateCalculatedCorrectly() {
    // ARRANGE

    Species__c specie = [
      SELECT Id
      FROM Species__c
      LIMIT 1
    ];

    Plant__c plant = new Plant__c(
      Species__c = specie.Id,
      Last_Watered__c = System.today(),
      Last_Fertilization__c = System.today()
    );

    // ACT

    Test.startTest();

    insert plant;

    Test.stopTest();

    // ASSERT

    plant = [
      SELECT Next_Fertilization__c
      FROM Plant__c
      WHERE Id = :plant.Id
    ];

    System.assertEquals(
      System.today() + 30,
      plant.Next_Fertilization__c,
      'La fecha de siguiente fertilizacion debe ser 30 dias despues'
    );
  }
}